In [141]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.neighbors import LocalOutlierFactor
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process.kernels import *
from sklearn.gaussian_process import GaussianProcessRegressor

In [80]:
df_X_train = pd.read_csv('X_train.csv')
df_y_train =  pd.read_csv('y_train.csv')
df_X_test =  pd.read_csv('X_test.csv')

In [81]:
df_X_train = df_X_train.drop(columns=['id'])
y_train = df_y_train.drop(columns=['id'])
df_X_test = df_X_test.drop(columns=['id'])

In [82]:
df_X_test.shape

(776, 832)

In [83]:
df_X_test.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,14655.540585,9917.388635,3368.691863,104367.124458,104.132894,95.412138,9222.286185,NaN,10054.751221,8.735165,...,9153.072463,12039.009308,714.005017,105.651509,103.574436,2628.082823,2.766271,1553.285942,1037.998392,9762.400011
1,13875.822363,9955.163751,3118.195658,103577.269601,103.290975,86.916779,9625.725002,10592.011548,10234.818476,10.853218,...,9915.292110,12579.041315,695.070183,106.900274,105.241730,2388.096545,NaN,1386.519117,1088.519466,11748.788738
2,14807.162495,10682.476988,3335.687716,106647.642610,109.481676,86.476353,9128.693785,10880.979240,10485.268796,10.294348,...,9733.845509,11009.075093,663.093857,105.541065,101.875603,2097.004365,2.362592,1204.527342,1067.697534,12487.217965
3,12253.667985,9001.609788,2631.482012,91105.570966,108.741037,84.542046,9765.458299,10953.438053,10190.986014,9.159968,...,11204.016625,9395.016940,656.018142,104.816602,107.213434,2035.045976,3.052844,794.341243,NaN,7931.828963
4,18925.988003,12161.366373,3724.006508,110262.565336,102.085795,107.920270,9494.243179,10684.550944,10074.187696,10.372417,...,11093.701929,13876.039832,964.037692,104.557952,109.185247,2971.082813,2.571392,1207.265749,1013.661254,8241.962297

In [84]:
df_X_train.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,14168.823171,10514.380717,3316.149698,94230.695124,102.386606,92.677127,11108.748199,10866.505510,10837.622093,10.227734,...,NaN,12352.094085,846.014651,105.132144,102.112809,2090.004260,2.691845,1234.374109,1000.784475,9285.751272
1,17757.037554,NaN,4101.016273,92959.527633,NaN,99.855168,10013.959449,10826.607494,10076.101597,11.436970,...,NaN,16198.071494,776.084467,106.385590,103.472030,2474.051881,2.287976,NaN,1012.626705,11750.284764
2,14226.656663,11029.642499,NaN,124055.600561,100.542483,92.860892,NaN,10492.342868,NaN,10.810076,...,10329.704431,13976.063780,737.040332,103.671234,109.458246,2656.083281,2.843706,888.353607,1048.810385,9553.922728
3,8766.012436,7384.202998,2147.308418,100157.719990,104.855061,101.929026,10050.049932,10499.521099,10525.030989,10.092109,...,10008.251395,6212.127347,329.044233,105.084488,104.858546,1097.785204,2.732257,927.752967,1048.357330,NaN
4,13801.016418,13269.493652,3408.316953,92048.527786,103.759758,95.789235,9667.353978,10750.783106,10618.800750,12.006773,...,10095.782015,13772.061493,NaN,NaN,100.369834,2693.053231,2.702908,1471.354073,1071.284484,9423.533063

In [86]:
imputer = KNNImputer(n_neighbors=2)

X_train_i = imputer.fit_transform(df_X_train)
X_test_i = imputer.fit_transform(df_X_test)


X_train_im = pd.DataFrame(X_train_i, columns=df_X_train.columns)
X_test_im = pd.DataFrame(X_test_i, columns=df_X_test.columns)

In [87]:
lof = LocalOutlierFactor(n_neighbors=2)
pred_train = lof.fit_predict(X_train_im)
pred_test = lof.fit_predict(X_test_im)

In [90]:
X_train_im['outlier_lof'] = pred_train
X_test_im['outlier_lof'] = pred_test
y_train['outlier_lof'] = pred_train

In [92]:
X_train_im

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x823,x824,x825,x826,x827,x828,x829,x830,x831,outlier_lof
0,14168.823171,10514.380717,3316.149698,94230.695124,102.386606,92.677127,11108.748199,10866.505510,10837.622093,10.227734,...,12352.094085,846.014651,105.132144,102.112809,2090.004260,2.691845,1234.374109,1000.784475,9285.751272,-1
1,17757.037554,9990.515000,4101.016273,92959.527633,103.784620,99.855168,10013.959449,10826.607494,10076.101597,11.436970,...,16198.071494,776.084467,106.385590,103.472030,2474.051881,2.287976,1390.744647,1012.626705,11750.284764,1
2,14226.656663,11029.642499,3289.867648,124055.600561,100.542483,92.860892,11438.615618,10492.342868,10038.488345,10.810076,...,13976.063780,737.040332,103.671234,109.458246,2656.083281,2.843706,888.353607,1048.810385,9553.922728,1
3,8766.012436,7384.202998,2147.308418,100157.719990,104.855061,101.929026,10050.049932,10499.521099,10525.030989,10.092109,...,6212.127347,329.044233,105.084488,104.858546,1097.785204,2.732257,927.752967,1048.357330,8838.401233,1
4,13801.016418,13269.493652,3408.316953,92048.527786,103.759758,95.789235,9667.353978,10750.783106,10618.800750,12.006773,...,13772.061493,756.570876,103.767286,100.369834,2693.053231,2.702908,1471.354073,1071.284484,9423.533063,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,18707.457475,13610.725702,3785.886941,113497.632841,109.526764,97.812339,11274.011935,10803.953566,10949.811419,10.868003,...,17727.003274,1033.057071,104.838553,102.235191,3099.069091,3.079234,1362.889974,1020.651568,10110.360570,1
1208,17108.239122,12168.536128,3442.619145,98218.773311,100.468476,109.994258,11031.326117,10231.743317,10687.321177,10.238957,...,14721.087037,792.061138,105.823015,109.915094,3124.059793,2.935047,1577.404870,1026.749434,10620.330033,1
1209,14264.707321,9273.405761,3580.894003,101668.927699,102.620705,104.470375,9159.594864,10661.827392,10623.176915,10.132906,...,15226.056342,831.025190,101.926717,101.669153,2252.031870,2.434948,1781.799720,1066.379647,10317.757445,1
1210,14907.077440,10936.636575,3159.167789,100400.608972,106.622507,84.859872,10356.404262,10107.960852,10384.924460,8.239864,...,12976.062457,852.001070,103.098317,104.397562,2585.048660,2.731768,1300.379678,1049.370040,10876.010268,1
1211,14975.969273,11451.350347,3107.470343,100080.295868,108.040548,102.941177,10766.888640,10726.567333,10632.289329,10.687628,...,12953.077245,919.051273,107.668141,102.999153,2489.012323,2.721068,1416.819713,1088.315592,10359.138969,1

In [93]:
X_train_im = X_train_im[X_train_im.outlier_lof != -1]
X_test_im = X_test_im[X_test_im.outlier_lof != -1]
y_train = y_train[y_train.outlier_lof != -1]

In [95]:
X_train_f = X_train_im.drop(columns=['outlier_lof'])
y_train = y_train.drop(columns=['outlier_lof'])
X_test_f = X_test_im.drop(columns=['outlier_lof'])

In [49]:
X_test_f.shape #thats a problem

(697, 832)

In [128]:
np.seterr(invalid='ignore')
new_datax = X_train_f
#feature selection train
selector = SelectKBest(f_regression, k=200)
new_datax_reduced = selector.fit_transform(new_datax, np.array(y_train).ravel())
cols = selector.get_support(indices=True)

C:\Users\sedri\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:289: RuntimeWarning: divide by zero encountered in true_divide
  correlation_coefficient /= X_norms

In [130]:
#scale 
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(new_datax_reduced)
X_scaled = scaler.transform(new_datax_reduced)

In [142]:
kernel = 1.0 * RBF(1.0)
kernel = RationalQuadratic()
regressor = GaussianProcessRegressor(kernel=kernel)

In [143]:
from sklearn.model_selection import cross_validate
scores = cross_validate(regressor, X_train_f, y_train, cv=5,
                    scoring=('r2'),
                    return_train_score=True,
                    n_jobs=4)

In [145]:
print(scores['test_score'])

[-55.99200715 -51.44093605 -56.5816176  -51.69759761 -48.25867389]