In [4]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.neighbors import LocalOutlierFactor
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process import GaussianProcessRegressor

In [5]:
df_X_train = pd.read_csv('/Users/sanjanawarambhey/Downloads/task1/X_train.csv')
df_y_train =  pd.read_csv('/Users/sanjanawarambhey/Downloads/task1/y_train.csv')
df_X_test =  pd.read_csv('/Users/sanjanawarambhey/Downloads/task1/X_test.csv')
df_sample =  pd.read_csv('/Users/sanjanawarambhey/Downloads/task1/sample.csv')

In [6]:
df_X_train = df_X_train.drop(columns=['id'])
y_train = df_y_train.drop(columns=['id'])
df_X_test = df_X_test.drop(columns=['id'])

In [7]:
df_X_test.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,14655.540585,9917.388635,3368.691863,104367.124458,104.132894,95.412138,9222.286185,NaN,10054.751221,8.735165,...,9153.072463,12039.009308,714.005017,105.651509,103.574436,2628.082823,2.766271,1553.285942,1037.998392,9762.400011
1,13875.822363,9955.163751,3118.195658,103577.269601,103.290975,86.916779,9625.725002,10592.011548,10234.818476,10.853218,...,9915.292110,12579.041315,695.070183,106.900274,105.241730,2388.096545,NaN,1386.519117,1088.519466,11748.788739
2,14807.162495,10682.476988,3335.687716,106647.642610,109.481676,86.476353,9128.693785,10880.979240,10485.268796,10.294348,...,9733.845509,11009.075093,663.093857,105.541065,101.875603,2097.004365,2.362592,1204.527342,1067.697534,12487.217965
3,12253.667985,9001.609788,2631.482012,91105.570966,108.741037,84.542046,9765.458299,10953.438053,10190.986014,9.159968,...,11204.016625,9395.016940,656.018142,104.816602,107.213434,2035.045976,3.052844,794.341243,NaN,7931.828963
4,18925.988003,12161.366373,3724.006508,110262.565336,102.085795,107.920270,9494.243179,10684.550944,10074.187696,10.372417,...,11093.701929,13876.039832,964.037692,104.557952,109.185247,2971.082813,2.571392,1207.265749,1013.661254,8241.962297

In [8]:
df_X_train.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
0,14168.823171,10514.380717,3316.149698,94230.695124,102.386606,92.677127,11108.748199,10866.505510,10837.622093,10.227734,...,NaN,12352.094085,846.014651,105.132144,102.112809,2090.004260,2.691845,1234.374109,1000.784475,9285.751272
1,17757.037554,NaN,4101.016273,92959.527633,NaN,99.855168,10013.959449,10826.607494,10076.101597,11.436970,...,NaN,16198.071494,776.084467,106.385590,103.472030,2474.051881,2.287976,NaN,1012.626705,11750.284764
2,14226.656663,11029.642499,NaN,124055.600561,100.542483,92.860892,NaN,10492.342868,NaN,10.810076,...,10329.704431,13976.063780,737.040332,103.671234,109.458246,2656.083281,2.843706,888.353607,1048.810385,9553.922728
3,8766.012436,7384.202998,2147.308418,100157.719990,104.855061,101.929026,10050.049932,10499.521099,10525.030989,10.092109,...,10008.251395,6212.127347,329.044233,105.084488,104.858546,1097.785204,2.732257,927.752967,1048.357330,NaN
4,13801.016418,13269.493652,3408.316953,92048.527786,103.759757,95.789235,9667.353978,10750.783106,10618.800750,12.006773,...,10095.782015,13772.061493,NaN,NaN,100.369834,2693.053231,2.702908,1471.354073,1071.284484,9423.533063

In [9]:
imputer = KNNImputer(n_neighbors=2)

X_train_i = imputer.fit_transform(df_X_train)
X_test_i = imputer.fit_transform(df_X_test)


X_train_im = pd.DataFrame(X_train_i, columns=df_X_train.columns)
X_test_im = pd.DataFrame(X_test_i, columns=df_X_test.columns)

In [10]:
lof = LocalOutlierFactor(n_neighbors=2)
pred_train = lof.fit_predict(X_train_im)
pred_test = lof.fit_predict(X_test_im) 

X_train_im['outlier_lof'] = pred_train
X_test_im['outlier_lof'] = pred_test
y_train['outlier_lof'] = pred_train

X_train_im = X_train_im[X_train_im.outlier_lof != -1]
X_test_im = X_test_im[X_test_im.outlier_lof != -1]
y_train = y_train[y_train.outlier_lof != -1] 


X_train_f = X_train_im.drop(columns=['outlier_lof'])
y_train = y_train.drop(columns=['outlier_lof'])
X_test_f = X_test_im.drop(columns=['outlier_lof'])

In [11]:
selector = SelectKBest(score_func=f_regression, k=200)
X_train_s = selector.fit_transform(X_train_f, np.array(y_train).ravel())

X_test_s = selector.transform(X_test_f)
X_train_se = pd.DataFrame(X_train_s)
X_test_se = pd.DataFrame(X_test_s)

/Users/sanjanawarambhey/opt/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py:299: RuntimeWarning: invalid value encountered in true_divide
  corr /= X_norms

In [12]:
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train_se)
X_test_sc = scaler.transform(X_test_se)


X_train = pd.DataFrame(X_train_sc, columns=X_train_se.columns)
X_test = pd.DataFrame(X_test_sc, columns=X_test_se.columns)

In [13]:
kernel = 1.0 * RBF(1.0)
regressor = GaussianProcessRegressor(kernel=kernel).fit(X_train, y_train)

:

: